{% set version = "0.5.6" %}

package:
  name: pystow
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/p/pystow/pystow-{{ version }}.tar.gz
  sha256: db567e82a5b7aea34cdcf4ae00ba822cd64a51ae2f465b1995599676e4cdbff2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - click
    - requests
    - tqdm

test:
  requires:
    - python {{ python_min }}
    - pip
  imports:
    - pystow
  commands:
    - pip check

about:
  home: https://github.com/cthoyt/pystow
  summary: Easily pick a place to store data for your python package.
  license: MIT
  license_file:
    - LICENSE
  doc_url: https://pystow.readthedocs.io/en/latest/
  dev_url: https://github.com/cthoyt/pystow

extra:
  recipe-maintainers:
    - cthoyt
    - jamesmyatt
